# Default values for qycloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets:
- name: harbor-registry-secret

frontend:
  replicaCount: 1
  nginx:
    image: "dockerhub.aysaas.com/library/aysaas/nginx"
    imageTag: "1.13.7-alpine"
    pullPolicy: IfNotPresent
    containerPort: 80

  php:
    image: "dockerhub.aysaas.com/library/aysaas/php"
    imageTag: "7.0-ubuntu-14.04-dev"
    pullPolicy: Always
    containerPort: 9000
    env:
      environment: "production"

  source:
    image: "dockerhub.aysaas.com/library/aysaas/saas"
    imageTag: "master"
    pullPolicy: Always

  nodeBuild:
    image: "dockerhub.aysaas.com/library/aysaas/node"
    imageTag: "9.3.0-alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 100m
      memory: 100Mi


beanstalkd:
  replicaCount: 1
  image: "dockerhub.aysaas.com/library/aysaas/beanstalkd"
  imageTag: "1.10-alpine"
  pullPolicy: IfNotPresent
  containerPort: 11300
  service:
    type: ClusterIP
    port: 11300
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

mongo:
  replicaCount: 1
  image: "dockerhub.aysaas.com/library/aysaas/mongo"
  imageTag: "3.4.10-jessie"
  pullPolicy: IfNotPresent
  containerPort: 27017
  service:
    type: ClusterIP
    port: 27017
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  env:
    auth: "no"
    adminPassword: root
    adminUser: root
    appDatabase: qycloud
    appDatabaseUser: root
    appDatabasePassword: root

mysql:
  replicaCount: 1
  image: "dockerhub.aysaas.com/library/aysaas/mysql"
  imageTag: "5.6.38-jessie"
  pullPolicy: IfNotPresent
  containerPort: 3306
  service:
    type: ClusterIP
    port: 3306
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  env:
    appDatabase: master
    rootPassword: 123456

redis:
  replicaCount: 1
  image: "dockerhub.aysaas.com/library/aysaas/redis"
  imageTag: "4.0.6-alpine"
  pullPolicy: IfNotPresent
  containerPort: 6379
  service:
    type: ClusterIP
    port: 6379
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

persistence:
  enabled: true
  ## If defined, PVC must be created manually before volume will be bound
#  existingClaim: "saas-saas"

  accessMode: ReadWriteMany
  size: 8Gi
  storageClass: "aysaas-nfs-once"


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  domain: default.com
  hosts:
    master: www
    static: static
    fileio: fileio
    xhprof: xhprof
    queue: queue

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
