apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: "kube-system"
spec:
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      containers:
      - name: provisioner
        image: quay.io/external_storage/local-volume-provisioner:v1.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: discovery-vol
          mountPath: "/local-disks"
        - name: local-volume-config
          mountPath: /etc/provisioner/config/
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      volumes:
      - name: discovery-vol
        hostPath:
          path: "/mnt/disks"
      - configMap:
          defaultMode: 420
          name: local-volume-config
        name: local-volume-config
      serviceAccount: local-storage-admin
