- name: 获取 kubeadm.conf
  become: yes
  copy: src=roles/kubeadm/files/kubeadm.conf dest=/root/kubeadm.conf mode=0644

#- name: kubeadm init
#  become: yes
#  shell: kubeadm reset && kubeadm init --config /root/kubeadm.conf
#  register: shell_result
#  async: 45
#  poll: 5
#
#- name: kubeadm init
#  debug:
#    var: shell_result.stdout_lines

- name: kubectl config
  shell: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Installing a pod network with Flannel
  copy: src=roles/kubeadm/files/kube-flannel.yml dest=$HOME/kube-flannel.yml mode=0644
  tags: flannel

- import_tasks: roles/kubeadm/tasks/kubelet-status.yml
