- name: Kerbernetes | Exec kubeadm init
  become: yes
  shell: kubeadm reset && kubeadm init --config /root/kubeadm.conf
  register: shell_result
  async: 45
  poll: 5


- name: Kerbernetes | Cat kubeadm init
  debug:
    var: shell_result.stdout_lines


- name: Kerbernetes | Save kubeadm_join string
  replace:
    dest: roles/kubeadm/node/defaults/main.yml
    regexp: '^kubeadm_join:.*$'
    replace: "kubeadm_join: {{ shell_result.stdout_lines[-1].strip() }}"
  delegate_to: localhost
  ignore_errors: True
  tags: set-kubeadm-join


- name: Kerbernetes | Do kubectl config
  become: yes
  shell: mkdir -p $HOME/.kube && sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config


- include_tasks: kubelet.yml


- name: Kerbernetes | Install a pod network with Flannel
  become: yes
  shell: kubectl apply -f $HOME/kube-flannel.yml
  tags: flannel
