kind: ConfigMap
apiVersion: v1
metadata:
  name: qycloud-config
data:
  aysaas.conf: |-
    server {
      server_name www.master.aysaas.com;

      root /opt/saas/public;

      # index index.html index.htm index.php;
      location /global/svgweb/ {
        break;
      }


      location /global/jquery/extend/uploadify/ {
        break;
      }

      location /global/pdf2swf/ {
        break;
      }

      location /form/render/ueditor/ {
        break;
      }

      location /favicon.ico {
        break;
        access_log off;
        log_not_found off;
      }

      location / {
        rewrite . /index.php;
      }

      location ^~ /getway/ {
        rewrite . /index.php;
      }

      location ~ \.php$ {
        if ($request_uri ~ "^/service_org") {
          root /opt/org/public;
        }
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      server_name static.master.aysaas.com;

      root /opt/saas/public;

      location / {
        access_log off;
      }

      location ~ \.php$ {
        deny all;
      }

      location ~* \.(eot|ttf|woff)$ {
        add_header Access-Control-Allow-Origin *;
      }

      location /form/render/ueditor/ {
        rewrite ^/form/render/ueditor/(.*)$ /components/ueditor/$1 permanent;
      }
    }

    server {
      server_name fileio.master.aysaas.com;
      root /opt/saas/public;
      client_max_body_size 128m;
      location /crossdomain.xml {
        break;
      }

      location / {
        rewrite . /index.php ;
      }

      location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      server_name xhprof.master.aysaas.com;
      #auth_basic "[Tips]";
      #auth_basic_user_file /etc/nginx/conf.d/[USER];
      error_log /var/log/nginx/tools-error.log error;
      access_log /var/log/nginx/tools-access.log combined;

      root /opt/utils/xhprof/xhprof_html;

      index index.php index.html;

      location / {
      }

      location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      server_name queue.master.aysaas.com;
      #auth_basic "[Tips]";
      #auth_basic_user_file /etc/nginx/conf.d/[USER];
      error_log /var/log/nginx/beanstalkd-console-error.log error;
      access_log /var/log/nginx/beanstald-console-access.log combined;

      root /opt/beanstalkd-console/public;

      index index.php index.html;

      location / {
      }

      location ~* \.(css)$ {
        add_header Content-Type text/css;
      }

      location ~* \.(eot|ttf|woff)$ {
        add_header Access-Control-Allow-Origin *;
      }

      location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }