version: '3'
services:
  web:
    image: nginx:1.13.7-alpine
    restart: always
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./charts:/srv/charts
    ports:
     - "8079:80"

