- name: iptables settings
  become: yes
  shell: grep "^net.bridge.bridge-nf-call-arptables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-arptables = 1" >> /etc/sysctl.conf; grep "^net.bridge.bridge-nf-call-iptables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf; grep "^net.bridge.bridge-nf-call-ip6tables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf; sysctl -p >>/dev/null

- name: kubeadm join
  become: yes
  shell: "{{ kubeadm_join }}"
  register: shell_result
  async: 45
  poll: 5

- name: kubeadm join
  debug:
    var: shell_result.stdout_lines

- include_tasks: roles/kubeadm/master/tasks/kubelet.yml