- name: 更改 hostname
  become: yes
  hostname:
    name: "{{ NODE_NAME }}"
  tags: hostname

- name: Hosts | add hostname to /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ NODE_NAME }}'
    state: present
  tags: hostname

- name: Hosts | add cluster node to /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for host in groups['kube-cluster'] %}
      {{ host }}    {{ hostvars[host]['NODE_NAME']}}
      {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# Ansible Inventory Hosts {mark}"
  tags: hosts

- import_tasks: restart.yml

- name: 查看 hostname
  become: yes
  shell: hostname
  register: shell_result
  tags: check-status

- name: 查看 hostname
  debug:
    var: shell_result.stdout_lines
  tags: check-status
