- name: Hostname | Set hostname
  become: yes
  hostname:
    name: "{{ NODE_NAME }}"
  tags: set-hostname

- name: Hosts | Add hostname to /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ NODE_NAME }}'
    state: present
  tags: set-hostname

- name: Hosts | Add cluster node to /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for host in groups['kube-cluster'] %}
      {{ host }}    {{ hostvars[host]['NODE_NAME']}}
      {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# Ansible Inventory Hosts {mark}"
  tags: set-hosts
