- name: Init | Config /etc/cloud/cloud.cfg
  become: yes
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^.*preserve_hostname.*$'
    line: 'preserve_hostname: true'
    state: present
  tags: config-hosts


- name: Init | Config hostname
  become: yes
  hostname:
    name: "{{ NODE_NAME }}"
  tags: config-hosts


- name: Init | Add hostname to /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ NODE_NAME }}'
    state: present
  tags: config-hosts


- name: Init | Add cluster node to /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for host in groups['kube-cluster'] %}
      {{ host }}    {{ hostvars[host]['NODE_NAME']}}
      {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# Ansible Inventory Hosts {mark}"
  tags: config-hosts


- name: Init | Check /etc/hosts
  become: yes
  shell: cat /etc/hosts
  register: shell_result
  tags: check-hosts


- name: Init | Check hostname
  debug:
    var: shell_result.stdout_lines
  tags: check-hosts


