#- name: Install the package "python 2.7"
#  sudo: yes
#  raw: sudo apt-get update && sudo apt-get -y install python-2.7
- name: Init | ssh-copy-id ~/.ssh
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh-copy


- name: Init | Check OS Distribution (Support Ubuntu 16.04+)
  assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_major_version >= 16"
    msg: "recommend Ubuntu 16.04+"
  tags: check-os


# sudo sed -i 's/mirrors.ustc.edu.cn/cn.archive.ubuntu.com/g' /etc/apt/sources.list
- name: Init | Switch to USTC mirror for apt
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: 'cn.archive.ubuntu.com'
    replace: 'mirrors.ustc.edu.cn'
  tags: config-apt, config-apt-sources


- name: Init | Add USTC Public Key for apt
  become: yes
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7EA0A9C3F273FCD8 6A030B21BA07F4FB
  tags: config-apt


- name: Init | Remove arch-i386 from apt
  become: yes
  shell: dpkg --remove-architecture i386
  tags: config-apt


- name: Init | Apt-get update
  become: yes
  apt:
    update_cache: yes
  tags: config-apt


- name: Init | Put alias file
  become: yes
  copy: src=alias.rc dest=/etc/profile.d/alias.sh mode=0644
  tags: config-alias


- name: Init | Config alias for root
  become: yes
  lineinfile:
    dest: /root/.bashrc
    regexp: '^.*alias\.sh.*$'
    line: 'source /etc/profile.d/alias.sh'
    state: present
  tags: config-alias


- name: Init | Config alias for current user
  lineinfile:
    dest: ~/.bashrc
    regexp: '^.*alias\.sh.*$'
    line: 'source /etc/profile.d/alias.sh'
    state: present
  tags: config-alias


- name: Init | Config gitconfig for root
  become: yes
  copy: src=gitconfig dest=/root/.gitconfig mode=0644
  tags: config-git


- import_tasks: hostname.yml


