#- name: Install the package "python 2.7"
#  sudo: yes
#  raw: sudo apt-get update && sudo apt-get -y install python-2.7

- name: Set authorized key for user ubuntu copying it from current user
  authorized_key:
    user: anyuan
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Check CFSSL exists
  become: yes
  stat:
    path: "/usr/local/bin/cfssl"
  register: cfssl_stat

- name: 安装 CFSSL
  become: yes
  copy: src=bin/{{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson
  when: cfssl_stat.stat.exists == False

- name: 更换 APT 源为 UST
  become: yes
  copy: src=sources.list-16.04 dest=/etc/apt/sources.list mode=0644

- name: 添加 USTC Public Key
  become: yes
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3746C208A7317B0F

- name: 更新 APT
  become: yes
  shell: apt-get update

- name: 设置别名
  become: yes
  copy: src=alias.rc dest=/etc/profile.d/alias.sh mode=0644

- name: 设置 gitconfig
  become: yes
  copy: src=gitconfig dest=/root/.gitconfig mode=0644
  tags: config

- import_tasks: hostname.yml


