#- name: Install the package "python 2.7"
#  sudo: yes
#  raw: sudo apt-get update && sudo apt-get -y install python-2.7

- name: SSH | Ssh-copy-id ~/.ssh
  authorized_key:
    user: anyuan
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

## Kubeadm don't use cfssl
#- name: Check CFSSL exists
#  become: yes
#  stat:
#    path: "/usr/local/bin/cfssl"
#  register: cfssl_stat

#- name: 安装 CFSSL
#  become: yes
#  copy: src=bin/{{ item }} dest=/usr/local/bin/{{ item }} mode=0755
#  with_items:
#  - cfssl
#  - cfssl-certinfo
#  - cfssljson
#  when: cfssl_stat.stat.exists == False

- name: APT | Replace with USTC mirror
  become: yes
  copy: src=sources.list-16.04 dest=/etc/apt/sources.list mode=0644
  tags: config-apt

- name: APT | Add USTC Public Key
  become: yes
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3746C208A7317B0F
  tags: config-apt

- name: Config | Set alias
  become: yes
  copy: src=alias.rc dest=/etc/profile.d/alias.sh mode=0644
  tags: config-alias

- name: Config | Enable alias
  become: yes
  lineinfile:
    dest: /root/.bashrc
    regexp: '^.*alias\.sh.*$'
    line: 'source /etc/profile.d/alias.sh'
    state: present
  tags: config-alias

- name: Config | Set gitconfig
  become: yes
  copy: src=gitconfig dest=/root/.gitconfig mode=0644
  tags: config-git

- import_tasks: hostname.yml


