apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostAliases:
      # kube-master ip
#      - ip: "192.168.0.173"
      - ip: "127.0.0.1"
        hostnames:
          - "www.master.aysaas.com"
          - "static.master.aysaas.com"
          - "fileio.master.aysaas.com"
          - "update.master.aysaas.com"
      imagePullSecrets:
      - name: harbor-registry-secret

      initContainers:
      - name: init-beanstalkd
        image: busybox
        command: ['sh', '-c', 'until nslookup beanstalkd; do echo waiting for qycloud-beanstalkd; sleep 2; done;']
      - name: init-mongo
        image: busybox
        command: ['sh', '-c', 'until nslookup mongo; do echo waiting for qycloud-mongo; sleep 2; done;']
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for qycloud-mysql; sleep 2; done;']
      - name: init-redis
        image: busybox
        command: ['sh', '-c', 'until nslookup redis; do echo waiting for qycloud-redis; sleep 2; done;']

      containers:
      - name: nginx
        image: dockerhub.aysaas.com/library/aysaas/nginx:1.13.7-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: saas-nfs
            mountPath: "/opt"
          - name: nginx-aysaas-config
            mountPath: "/etc/nginx/conf.d/"

      - name: php
        image: dockerhub.aysaas.com/library/aysaas/php:7.0-ubuntu-14.04-dev
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          value: production
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_HOST
          value: mysql
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: saas-nfs
            mountPath: "/opt"

      volumes:
      - name: nginx-aysaas-config
        configMap:
          name: qycloud-config
      - name: saas-nfs
        persistentVolumeClaim:
          claimName: saas-saas
