#!/usr/bin/env bash

HELM_HOME_DIR="/root/.helm"

SSL_CA_DIR=/usr/share/ca-certificates

docker run --rm \
  --net=host \
  --name=helm \
  -v ${HOME}/.kube/config:${HOME}/.kube/config:ro \
  -v /etc/ssl:/etc/ssl:ro \
  -v ${HELM_HOME_DIR}:${HELM_HOME_DIR}:rw \
  -v ${SSL_CA_DIR}:${SSL_CA_DIR}:ro \
  -e KUBECONFIG=${HOME}/.kube/config \
  lachlanevenson/k8s-helm:v2.7.2 \
  "$@"

#  -e http_proxy="{{proxy_env.http_proxy}}" \
#  -e https_proxy="{{proxy_env.https_proxy}}" \
#  -e no_proxy="{{proxy_env.no_proxy}}" \
