{{- $fullName := "127.0.0.1" -}}
{{- $phpFastcgiPort := .Values.frontend.php.containerPort -}}
{{- $masterServerName := .Values.ingress.hosts.master -}}
{{- $staticServerName := .Values.ingress.hosts.static -}}
{{- $fileioServerName := .Values.ingress.hosts.fileio -}}
{{- $xhprofServerName := .Values.ingress.hosts.xhprof -}}
{{- $queueConsoleServerName := .Values.ingress.hosts.queue -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "qycloud.fullname" . }}-config
  labels:
    app: {{ .Release.Name }}-config
    chart: {{ template "qycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  aysaas.conf: |-
    server {
      server_name {{ $masterServerName }};

      root /opt/saas/public;

      # index index.html index.htm index.php;
      location /global/svgweb/ {
        break;
      }


      location /global/jquery/extend/uploadify/ {
        break;
      }

      location /global/pdf2swf/ {
        break;
      }

      location /form/render/ueditor/ {
        break;
      }

      location /favicon.ico {
        break;
        access_log off;
        log_not_found off;
      }

      location / {
        rewrite . /index.php;
      }

      location ^~ /getway/ {
        rewrite . /index.php;
      }

      location ~ \.php$ {
        if ($request_uri ~ "^/service_org") {
          root /opt/org/public;
        }
        fastcgi_pass   {{ $fullName }}:{{ $phpFastcgiPort }};
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      server_name {{ $staticServerName }};

      root /opt/saas/public;

      location / {
        access_log off;
      }

      location ~ \.php$ {
        deny all;
      }

      location ~* \.(eot|ttf|woff)$ {
        add_header Access-Control-Allow-Origin *;
      }

      location /form/render/ueditor/ {
        rewrite ^/form/render/ueditor/(.*)$ /components/ueditor/$1 permanent;
      }
    }

    server {
      server_name {{ $fileioServerName }};
      root /opt/saas/public;
      client_max_body_size 128m;
      location /crossdomain.xml {
        break;
      }

      location / {
        rewrite . /index.php ;
      }

      location ~ \.php$ {
        fastcgi_pass   {{ $fullName }}:{{ $phpFastcgiPort }};
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      server_name {{ $xhprofServerName }};
      #auth_basic "[Tips]";
      #auth_basic_user_file /etc/nginx/conf.d/[USER];
      error_log /var/log/nginx/xhprof-error.log error;
      access_log /var/log/nginx/xhprof-access.log combined;

      root /opt/xhprof/xhprof/xhprof_html;

      index index.php index.html;

      location / {
      }

      location ~ \.php$ {
        fastcgi_pass   {{ $fullName }}:{{ $phpFastcgiPort }};
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      server_name {{ $queueConsoleServerName }};
      #auth_basic "[Tips]";
      #auth_basic_user_file /etc/nginx/conf.d/[USER];
      error_log /var/log/nginx/beanstalk-console-error.log error;
      access_log /var/log/nginx/beanstalk-console-access.log combined;

      root /opt/beanstalk-console/public;

      index index.php index.html;

      location / {
      }

      location ~* \.(css)$ {
        add_header Content-Type text/css;
      }

      location ~* \.(eot|ttf|woff)$ {
        add_header Access-Control-Allow-Origin *;
      }

      location ~ \.php$ {
        fastcgi_pass   {{ $fullName }}:{{ $phpFastcgiPort }};
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
      }
    }