{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serverDomain := .Values.ingress.domain | lower -}}
{{- $servicePort := .Values.nginx.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ template "qycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}.{{ $serverDomain }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $key, $value := .Values.ingress.hosts }}
    {{- if not (eq $key "portal") }}
    - host: {{ $value }}.{{ $serverDomain }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $releaseName }}-nginx
              servicePort: {{ $servicePort }}
    {{- end }}
  {{- end }}
    - host: {{ .Values.ingress.hosts.portal }}.{{ $serverDomain }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $releaseName }}-node
              servicePort: {{ .Values.node.containerPort }}
{{- end }}
