{{- if and .Values.persistence.mysql.enabled (not .Values.persistence.mysql.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "qycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.mysql.accessMode | quote }}

  resources:
    requests:
      storage: {{ .Values.persistence.mysql.size | quote }}

{{- if .Values.persistence.mysql.storageClass }}
{{- if (eq "-" .Values.persistence.mysql.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.mysql.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
