apiVersion: v1
kind: Service
metadata:
  name: {{ template "qycloud.fullname" . }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ template "qycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-redis
    release: {{ .Release.Name }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "qycloud.fullname" . }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ template "qycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.redis.image }}:{{ .Values.redis.imageTag }}"
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
