- name: Kerbernetes | Add Kerbernetes apt-repository
  become: yes
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^.*kubernetes.*$'
    line: "{{ kubernetes_apt_repository }}"
    state: present
  tags: config-kube-repo


- name: Kerbernetes | Apt-get update
  become: yes
  apt:
    update_cache: yes


- name: Kerbernetes | Install latest kubeadm kubectl kubelet
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "kubeadm"
    - "kubectl"
    - "kubelet"
    - "kubernetes-cni"
  when:
    - kubernetes_release == ""


- name: Kerbernetes | Install kubeadm kubectl kubelet by version
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "kubeadm-{{ kubernetes_release }}-00"
    - "kubectl-{{ kubernetes_release }}-00"
    - "kubelet-{{ kubernetes_release }}-00"
    - "kubernetes-cni-{{ kubernetes_cni_release }}-00"
  when:
    - kubernetes_release != ""


- name: Kerbernetes | Config kubelet pod-infra-container-image
  become: yes
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_EXTRA_ARGS='
    state: absent
  tags: config-kubelet


- name: Kerbernetes | Config kubelet pod-infra-container-image
  become: yes
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertbefore: '^ExecStart=$'
    line: 'Environment="KUBELET_EXTRA_ARGS={{ system_reserved }} {{ kube_reserved }} {{ eviction_hard }}"'
    state: present
  tags: config-kubelet


- name: Kerbernetes | Disable Swap - /etc/fstab
  become: yes
  replace:
    dest: /etc/fstab
    regexp: '(^[^#].*swap.*sw.*$)'
    replace: '# \1'
    backup: yes
  tags: config-swap


- name: Kerbernetes | Disable Swap - /etc/sysctl.d/k8s.conf
  become: yes
  lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    line: 'vm.swappiness=0'
    create: yes
    state: present
  tags: config-swap


- name: Kerbernetes | Disable Swap - sysctl
  become: yes
  shell: sysctl -p /etc/sysctl.d/k8s.conf && swapoff -a
  tags: config-swap


- name: Kerbernetes | Prepare kubeadm.conf
  become: yes
  copy: src=kubeadm.conf dest=/root/kubeadm.conf mode=0644
  tags: config-kubeadm
  when:
    - inventory_hostname in groups['kube-master']


#- name: Kerbernetes | Prepare flannel.conf
#  become: yes
#  copy: src=kube-flannel.yml dest=$HOME/kube-flannel.yml mode=0644


#- name: Kerbernetes | Install nfs-clinet for nsf-storage
#  become: yes
#  apt: name={{ item }} state=present
#  with_items:
#    - nfs-common
#  tags: install-nfs


#- name: Kerbernetes | iptables settings
#  become: yes
#  shell: grep "^net.bridge.bridge-nf-call-arptables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-arptables = 1" >> /etc/sysctl.conf; grep "^net.bridge.bridge-nf-call-iptables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf; grep "^net.bridge.bridge-nf-call-ip6tables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf; sysctl -p >>/dev/null
