- name: Kerbernetes | Install kubeadm kubectl kubelet
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - kubeadm
  - kubectl
  - kubelet
  - kubernetes-cni

- name: Kerbernetes | Config kubelet pod-infra-container-image
  become: yes
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_EXTRA_ARGS='
    state: absent
  tags: config-kubelet

- name: Kerbernetes | Config kubelet pod-infra-container-image
  become: yes
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertbefore: '^ExecStart=$'
    line: 'Environment="KUBELET_EXTRA_ARGS=--pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:3.1 --system-reserved=cpu=200m,memory=250Mi --kube-reserved=cpu=200m,memory=250Mi --eviction-hard=memory.available<500Mi,nodefs.available<5Gi,imagefs.available<5Gi"'
    state: present
  tags: config-kubelet

- name: Kerbernetes | Install nfs-clinet for nsf-storage
  become: yes
  apt: name={{ item }} state=present
  with_items:
  - nfs-common
  tags: install-nfs

- name: Kerbernetes | Disable Swap - /etc/fstab
  become: yes
  replace:
    dest: /etc/fstab
    regexp: '(^[^#].*swap.*sw.*$)'
    replace: '# \1'
    backup: yes
  tags: fstab

- name: Kerbernetes | Disable Swap - /etc/sysctl.d/k8s.conf
  become: yes
  lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    line: 'vm.swappiness=0'
    create: yes
    state: present
  tags: k8s-conf

- name: Kerbernetes | Disable Swap - sysctl
  become: yes
  shell: sysctl -p /etc/sysctl.d/k8s.conf && swapoff -a
  tags: swapoff

- name: Kerbernetes | Prepare kubeadm.conf
  become: yes
  copy: src=kubeadm.conf dest=/root/kubeadm.conf mode=0644
  tags: kubeadmconf

- name: Kerbernetes | Prepare flannel.conf
  become: yes
  copy: src=kube-flannel.yml dest=$HOME/kube-flannel.yml mode=0644
  tags: flannel-yaml

#- name: Kerbernetes | iptables settings
#  become: yes
#  shell: grep "^net.bridge.bridge-nf-call-arptables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-arptables = 1" >> /etc/sysctl.conf; grep "^net.bridge.bridge-nf-call-iptables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf; grep "^net.bridge.bridge-nf-call-ip6tables" /etc/sysctl.conf >>/dev/null || echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf; sysctl -p >>/dev/null
