- name: Docker | Add docker apt-repository
  become: yes
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^.*docker-ce.*$'
    line: "deb http://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present


- name: Docker | Apt-get update
  become: yes
  apt:
    update_cache: yes


- name: Docker | Install docker-ce
  become: yes
  ignore_errors: True
  apt:
    name: docker-ce
    state: present
    allow_unauthenticated: yes


- name: Docker | Prepare directory /etc/docker
  become: yes
  file: name={{ item }} state=directory
  with_items:
    - /etc/docker


- name: Docker | Config docker daemon.json
  become: yes
  copy: src=daemon.json dest=/etc/docker/daemon.json mode=0644
  tags: config-docker


- name: Docker | Restart docker
  become: yes
  shell: systemctl daemon-reload && systemctl enable docker && systemctl restart docker
  tags: config-docker


- name: Docker | Check docker status
  become: yes
  ignore_errors: True
  shell: systemctl status docker
  register: shell_result
  tags: check-docker


- name: Docker | Check docker status
  debug:
    var: shell_result.stdout_lines
  tags: check-docker


- name: Docker | Login Harbor Docker Registry
  become: yes
  shell: docker login private_docker_hub -u pull -p pull123Q
  when:
    - private_docker_hub != ""
  tags: docker-login
