- name: Install | Install docker-ce
  become: yes
  ignore_errors: True
  apt:
    name: docker-ce
    state: present
    allow_unauthenticated: yes

- name: Config | Prepare /etc/docker
  become: yes
  file: name={{ item }} state=directory
  with_items:
  - /etc/docker

- name: Config | Add docker registry
  become: yes
  copy: src=daemon.json dest=/etc/docker/daemon.json mode=0644

- name: Restart | Restart docker
  become: yes
  shell: systemctl daemon-reload && systemctl enable docker && systemctl restart docker

- name: Status | Check docker status
  become: yes
  ignore_errors: True
  shell: systemctl status docker
  register: shell_result
  tags: docker-status

- name: Status | Check docker status
  debug:
    var: shell_result.stdout_lines
  tags: docker-status

- name: Login | Login Harbor Docker Registry
  become: yes
  shell: docker login dockerhub.aysaas.com -u pull -p pull123Q
  tags: docker-login
